name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ruby2D dependencies
      run: sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Set XDG_RUNTIME_DIR
      run: echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
    - name: Run the default task
      run: bundle exec rake
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
